export interface Tool {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  route: string;
  usageCount?: string;
  featured?: boolean;
}

export interface Toolkit {
  id: string;
  name: string;
  description: string;
  icon: string;
  route: string;
  color: string;
  tools: Tool[];
  toolCount: number;
}

export const toolkits: Toolkit[] = [
  {
    id: 'pdf',
    name: 'PDF Toolkit',
    description: 'Complete PDF solution with 25 tools including merge, split, compress, convert, and OCR capabilities.',
    icon: 'fas fa-file-pdf',
    route: '/toolkit/pdf',
    color: 'red',
    toolCount: 25,
    tools: [
      {
        id: 'pdf-merger',
        name: 'PDF Merger',
        description: 'Combine multiple PDF files into one',
        category: 'PDF',
        icon: 'fas fa-file-contract',
        route: '/tool/pdf-merger',
        usageCount: '250K+',
        featured: true,
      },
      {
        id: 'pdf-splitter',
        name: 'PDF Splitter',
        description: 'Split PDF into separate pages',
        category: 'PDF',
        icon: 'fas fa-scissors',
        route: '/tool/pdf-splitter',
        usageCount: '180K+',
      },
      {
        id: 'pdf-compressor',
        name: 'PDF Compressor',
        description: 'Reduce PDF file size',
        category: 'PDF',
        icon: 'fas fa-file-archive',
        route: '/tool/pdf-compressor',
        usageCount: '320K+',
      },
      {
        id: 'pdf-to-word',
        name: 'PDF to Word',
        description: 'Convert PDF files to Word documents',
        category: 'PDF',
        icon: 'fab fa-microsoft',
        route: '/tool/pdf-to-word',
        usageCount: '200K+',
      },
      {
        id: 'pdf-to-excel',
        name: 'PDF to Excel',
        description: 'Convert PDF files to Excel spreadsheets',
        category: 'PDF',
        icon: 'fas fa-table',
        route: '/tool/pdf-to-excel',
        usageCount: '150K+',
      },
      {
        id: 'pdf-to-powerpoint',
        name: 'PDF to PowerPoint',
        description: 'Convert PDF files to PowerPoint presentations',
        category: 'PDF',
        icon: 'fas fa-presentation',
        route: '/tool/pdf-to-powerpoint',
        usageCount: '120K+',
      },
      {
        id: 'word-to-pdf',
        name: 'Word to PDF',
        description: 'Convert Word documents to PDF',
        category: 'PDF',
        icon: 'fas fa-file-import',
        route: '/tool/word-to-pdf',
        usageCount: '280K+',
      },
      {
        id: 'excel-to-pdf',
        name: 'Excel to PDF',
        description: 'Convert Excel files to PDF',
        category: 'PDF',
        icon: 'fas fa-chart-line',
        route: '/tool/excel-to-pdf',
        usageCount: '180K+',
      },
      {
        id: 'powerpoint-to-pdf',
        name: 'PowerPoint to PDF',
        description: 'Convert PowerPoint to PDF',
        category: 'PDF',
        icon: 'fas fa-chalkboard-teacher',
        route: '/tool/powerpoint-to-pdf',
        usageCount: '160K+',
      },
      {
        id: 'pdf-ocr',
        name: 'PDF OCR',
        description: 'Extract text from scanned PDFs',
        category: 'PDF',
        icon: 'fas fa-text-width',
        route: '/tool/pdf-ocr',
        usageCount: '140K+',
      },
      {
        id: 'pdf-watermark',
        name: 'PDF Watermark',
        description: 'Add watermarks to PDF files',
        category: 'PDF',
        icon: 'fas fa-certificate',
        route: '/tool/pdf-watermark',
        usageCount: '90K+',
      },
      {
        id: 'pdf-password-remover',
        name: 'PDF Password Remover',
        description: 'Remove password protection from PDFs',
        category: 'PDF',
        icon: 'fas fa-key',
        route: '/tool/pdf-password-remover',
        usageCount: '110K+',
      },
      {
        id: 'pdf-password-protector',
        name: 'PDF Password Protector',
        description: 'Add password protection to PDFs',
        category: 'PDF',
        icon: 'fas fa-shield-alt',
        route: '/tool/pdf-password-protector',
        usageCount: '130K+',
      },
      {
        id: 'pdf-rotator',
        name: 'PDF Rotator',
        description: 'Rotate PDF pages',
        category: 'PDF',
        icon: 'fas fa-sync-alt',
        route: '/tool/pdf-rotator',
        usageCount: '85K+',
      },
      {
        id: 'pdf-cropper',
        name: 'PDF Cropper',
        description: 'Crop PDF pages to specific dimensions',
        category: 'PDF',
        icon: 'fas fa-crop-alt',
        route: '/tool/pdf-cropper',
        usageCount: '75K+',
      },
      {
        id: 'pdf-page-extractor',
        name: 'PDF Page Extractor',
        description: 'Extract specific pages from PDF',
        category: 'PDF',
        icon: 'fas fa-copy',
        route: '/tool/pdf-page-extractor',
        usageCount: '95K+',
      },
      {
        id: 'pdf-page-numberer',
        name: 'PDF Page Numberer',
        description: 'Add page numbers to PDF',
        category: 'PDF',
        icon: 'fas fa-sort-numeric-down',
        route: '/tool/pdf-page-numberer',
        usageCount: '65K+',
      },
      {
        id: 'pdf-bookmark-manager',
        name: 'PDF Bookmark Manager',
        description: 'Add and manage PDF bookmarks',
        category: 'PDF',
        icon: 'fas fa-bookmark',
        route: '/tool/pdf-bookmark-manager',
        usageCount: '55K+',
      },
      {
        id: 'pdf-form-filler',
        name: 'PDF Form Filler',
        description: 'Fill PDF forms automatically',
        category: 'PDF',
        icon: 'fas fa-pen-square',
        route: '/tool/pdf-form-filler',
        usageCount: '80K+',
      },
      {
        id: 'pdf-signature-adder',
        name: 'PDF Signature Adder',
        description: 'Add digital signatures to PDF',
        category: 'PDF',
        icon: 'fas fa-file-signature',
        route: '/tool/pdf-signature-adder',
        usageCount: '70K+',
      },
      {
        id: 'pdf-text-extractor',
        name: 'PDF Text Extractor',
        description: 'Extract text content from PDF',
        category: 'PDF',
        icon: 'fas fa-quote-left',
        route: '/tool/pdf-text-extractor',
        usageCount: '125K+',
      },
      {
        id: 'pdf-image-extractor',
        name: 'PDF Image Extractor',
        description: 'Extract images from PDF files',
        category: 'PDF',
        icon: 'fas fa-photo-video',
        route: '/tool/pdf-image-extractor',
        usageCount: '105K+',
      },
      {
        id: 'pdf-organizer',
        name: 'PDF Organizer',
        description: 'Organize and rearrange PDF pages',
        category: 'PDF',
        icon: 'fas fa-sort-amount-down',
        route: '/tool/pdf-organizer',
        usageCount: '60K+',
      },
      {
        id: 'pdf-metadata-editor',
        name: 'PDF Metadata Editor',
        description: 'Edit PDF document properties',
        category: 'PDF',
        icon: 'fas fa-info-circle',
        route: '/tool/pdf-metadata-editor',
        usageCount: '45K+',
      },
      {
        id: 'pdf-version-converter',
        name: 'PDF Version Converter',
        description: 'Convert between PDF versions',
        category: 'PDF',
        icon: 'fas fa-code-branch',
        route: '/tool/pdf-version-converter',
        usageCount: '40K+',
      }
    ],
  },
  {
    id: 'image',
    name: 'Image Toolkit',
    description: 'Advanced image processing with 20 tools for resize, compress, convert, enhance, and AI-powered features.',
    icon: 'fas fa-image',
    route: '/toolkit/image',
    color: 'purple',
    toolCount: 20,
    tools: [
      {
        id: 'image-resizer',
        name: 'Image Resizer',
        description: 'Resize images to any dimension',
        category: 'Image',
        icon: 'fas fa-arrows-alt',
        route: '/tool/image-resizer',
        usageCount: '180K+',
        featured: true,
      },
      {
        id: 'bg-remover',
        name: 'AI Background Remover',
        description: 'Remove backgrounds automatically',
        category: 'Image',
        icon: 'fas fa-cut',
        route: '/tool/bg-remover',
        usageCount: '320K+',
        featured: true,
      },
      {
        id: 'image-compressor',
        name: 'Image Compressor',
        description: 'Reduce image file size',
        category: 'Image',
        icon: 'fas fa-file-archive',
        route: '/tool/image-compressor',
        usageCount: '280K+',
      },
      {
        id: 'image-converter',
        name: 'Image Converter',
        description: 'Convert between image formats',
        category: 'Image',
        icon: 'fas fa-random',
        route: '/tool/image-converter',
        usageCount: '350K+',
      },
      {
        id: 'image-cropper',
        name: 'Image Cropper',
        description: 'Crop images to specific dimensions',
        category: 'Image',
        icon: 'fas fa-crop-alt',
        route: '/tool/image-cropper',
        usageCount: '220K+',
      },
      {
        id: 'image-rotator',
        name: 'Image Rotator',
        description: 'Rotate and flip images',
        category: 'Image',
        icon: 'fas fa-sync-alt',
        route: '/tool/image-rotator',
        usageCount: '150K+',
      },
      {
        id: 'image-enhancer',
        name: 'AI Image Enhancer',
        description: 'Enhance image quality with AI',
        category: 'Image',
        icon: 'fas fa-wand-magic-sparkles',
        route: '/tool/image-enhancer',
        usageCount: '400K+',
        featured: true,
      },
      {
        id: 'image-upscaler',
        name: 'AI Image Upscaler',
        description: 'Upscale images with AI',
        category: 'Image',
        icon: 'fas fa-search-plus',
        route: '/tool/image-upscaler',
        usageCount: '300K+',
      },
      {
        id: 'image-colorizer',
        name: 'AI Image Colorizer',
        description: 'Add color to black and white images',
        category: 'Image',
        icon: 'fas fa-paint-brush',
        route: '/tool/image-colorizer',
        usageCount: '180K+',
      },
      {
        id: 'image-watermark-remover',
        name: 'Watermark Remover',
        description: 'Remove watermarks from images',
        category: 'Image',
        icon: 'fas fa-eraser',
        route: '/tool/image-watermark-remover',
        usageCount: '250K+',
      },
      {
        id: 'image-watermark-adder',
        name: 'Watermark Adder',
        description: 'Add watermarks to images',
        category: 'Image',
        icon: 'fas fa-signature',
        route: '/tool/image-watermark-adder',
        usageCount: '200K+',
      },
      {
        id: 'image-blur-tool',
        name: 'Image Blur Tool',
        description: 'Apply blur effects to images',
        category: 'Image',
        icon: 'fas fa-circle-notch',
        route: '/tool/image-blur-tool',
        usageCount: '120K+',
      },
      {
        id: 'image-brightness-adjuster',
        name: 'Brightness Adjuster',
        description: 'Adjust image brightness and contrast',
        category: 'Image',
        icon: 'fas fa-lightbulb',
        route: '/tool/image-brightness-adjuster',
        usageCount: '160K+',
      },
      {
        id: 'image-saturation-tool',
        name: 'Saturation Tool',
        description: 'Adjust image color saturation',
        category: 'Image',
        icon: 'fas fa-droplet',
        route: '/tool/image-saturation-tool',
        usageCount: '140K+',
      },
      {
        id: 'image-filter-effects',
        name: 'Filter Effects',
        description: 'Apply various filters to images',
        category: 'Image',
        icon: 'fas fa-layer-group',
        route: '/tool/image-filter-effects',
        usageCount: '190K+',
      },
      {
        id: 'image-border-adder',
        name: 'Border Adder',
        description: 'Add borders and frames to images',
        category: 'Image',
        icon: 'far fa-square',
        route: '/tool/image-border-adder',
        usageCount: '110K+',
      },
      {
        id: 'image-text-overlay',
        name: 'Text Overlay',
        description: 'Add text overlays to images',
        category: 'Image',
        icon: 'fas fa-text-height',
        route: '/tool/image-text-overlay',
        usageCount: '170K+',
      },
      {
        id: 'image-collage-maker',
        name: 'Collage Maker',
        description: 'Create photo collages',
        category: 'Image',
        icon: 'fas fa-th-large',
        route: '/tool/image-collage-maker',
        usageCount: '200K+',
      },
      {
        id: 'image-metadata-extractor',
        name: 'Metadata Extractor',
        description: 'Extract image metadata and EXIF data',
        category: 'Image',
        icon: 'fas fa-database',
        route: '/tool/image-metadata-extractor',
        usageCount: '80K+',
      },
      {
        id: 'meme-generator',
        name: 'Meme Generator',
        description: 'Create memes with custom text',
        category: 'Image',
        icon: 'fas fa-smile-beam',
        route: '/tool/meme-generator',
        usageCount: '300K+',
        featured: true,
      },
      {
        id: 'image-batch-processor',
        name: 'Batch Processor',
        description: 'Process multiple images at once',
        category: 'Image',
        icon: 'fas fa-clone',
        route: '/tool/image-batch-processor',
        usageCount: '130K+',
      }
    ],
  },
  {
    id: 'media',
    name: 'Media Toolkit',
    description: 'Professional audio and video tools with 20 converters, editors, and AI-enhanced processing capabilities.',
    icon: 'fas fa-play',
    route: '/toolkit/media',
    color: 'green',
    toolCount: 20,
    tools: [
      {
        id: 'audio-converter',
        name: 'Audio Converter',
        description: 'Convert between audio formats',
        category: 'Audio/Video',
        icon: 'fas fa-file-audio',
        route: '/tool/audio-converter',
        usageCount: '95K+',
        featured: true,
      },
      {
        id: 'video-converter',
        name: 'Video Converter',
        description: 'Convert between video formats',
        category: 'Audio/Video',
        icon: 'fas fa-file-video',
        route: '/tool/video-converter',
        usageCount: '180K+',
        featured: true,
      },
      {
        id: 'audio-compressor',
        name: 'Audio Compressor',
        description: 'Reduce audio file size',
        category: 'Audio/Video',
        icon: 'fas fa-compress-arrows-alt',
        route: '/tool/audio-compressor',
        usageCount: '120K+',
      },
      {
        id: 'video-compressor',
        name: 'Video Compressor',
        description: 'Reduce video file size',
        category: 'Audio/Video',
        icon: 'fas fa-file-archive',
        route: '/tool/video-compressor',
        usageCount: '200K+',
      },
      {
        id: 'audio-trimmer',
        name: 'Audio Trimmer',
        description: 'Trim and cut audio files',
        category: 'Audio/Video',
        icon: 'fas fa-scissors',
        route: '/tool/audio-trimmer',
        usageCount: '150K+',
      },
      {
        id: 'video-trimmer',
        name: 'Video Trimmer',
        description: 'Trim and cut video files',
        category: 'Audio/Video',
        icon: 'fas fa-cut',
        route: '/tool/video-trimmer',
        usageCount: '220K+',
      },
      {
        id: 'audio-merger',
        name: 'Audio Merger',
        description: 'Merge multiple audio files',
        category: 'Audio/Video',
        icon: 'fas fa-object-group',
        route: '/tool/audio-merger',
        usageCount: '90K+',
      },
      {
        id: 'video-merger',
        name: 'Video Merger',
        description: 'Merge multiple video files',
        category: 'Audio/Video',
        icon: 'fas fa-film',
        route: '/tool/video-merger',
        usageCount: '140K+',
      },
      {
        id: 'video-to-gif',
        name: 'Video to GIF',
        description: 'Convert videos to animated GIFs',
        category: 'Audio/Video',
        icon: 'fas fa-magic',
        route: '/tool/video-to-gif',
        usageCount: '250K+',
      },
      {
        id: 'gif-to-video',
        name: 'GIF to Video',
        description: 'Convert GIFs to video format',
        category: 'Audio/Video',
        icon: 'fas fa-play-circle',
        route: '/tool/gif-to-video',
        usageCount: '110K+',
      },
      {
        id: 'audio-volume-adjuster',
        name: 'Volume Adjuster',
        description: 'Adjust audio volume levels',
        category: 'Audio/Video',
        icon: 'fas fa-volume-up',
        route: '/tool/audio-volume-adjuster',
        usageCount: '130K+',
      },
      {
        id: 'audio-speed-changer',
        name: 'Speed Changer',
        description: 'Change audio playback speed',
        category: 'Audio/Video',
        icon: 'fas fa-gauge-high',
        route: '/tool/audio-speed-changer',
        usageCount: '85K+',
      },
      {
        id: 'video-speed-changer',
        name: 'Video Speed Changer',
        description: 'Change video playback speed',
        category: 'Audio/Video',
        icon: 'fas fa-forward',
        route: '/tool/video-speed-changer',
        usageCount: '160K+',
      },
      {
        id: 'video-frame-extractor',
        name: 'Frame Extractor',
        description: 'Extract frames from videos',
        category: 'Audio/Video',
        icon: 'fas fa-images',
        route: '/tool/video-frame-extractor',
        usageCount: '100K+',
      },
      {
        id: 'audio-noise-reducer',
        name: 'Noise Reducer',
        description: 'Remove noise from audio files',
        category: 'Audio/Video',
        icon: 'fas fa-volume-xmark',
        route: '/tool/audio-noise-reducer',
        usageCount: '170K+',
      },
      {
        id: 'video-subtitle-adder',
        name: 'Subtitle Adder',
        description: 'Add subtitles to videos',
        category: 'Audio/Video',
        icon: 'fas fa-comment-dots',
        route: '/tool/video-subtitle-adder',
        usageCount: '190K+',
      },
      {
        id: 'audio-equalizer',
        name: 'Audio Equalizer',
        description: 'Adjust audio frequency levels',
        category: 'Audio/Video',
        icon: 'fas fa-sliders',
        route: '/tool/audio-equalizer',
        usageCount: '75K+',
      },
      {
        id: 'video-watermark-adder',
        name: 'Video Watermark',
        description: 'Add watermarks to videos',
        category: 'Audio/Video',
        icon: 'fas fa-certificate',
        route: '/tool/video-watermark-adder',
        usageCount: '120K+',
      },
      {
        id: 'audio-format-info',
        name: 'Format Info',
        description: 'Get audio/video file information',
        category: 'Audio/Video',
        icon: 'fas fa-circle-info',
        route: '/tool/audio-format-info',
        usageCount: '60K+',
      },
      {
        id: 'volume-changer',
        name: 'Volume Changer',
        description: 'Adjust audio volume levels',
        category: 'Audio/Video',
        icon: 'fas fa-volume-high',
        route: '/tool/volume-changer',
        usageCount: '130K+',
      },
      {
        id: 'vocal-remover',
        name: 'Vocal Remover',
        description: 'Remove vocals from songs (Karaoke)',
        category: 'Audio/Video',
        icon: 'fas fa-microphone-lines-slash',
        route: '/tool/vocal-remover',
        usageCount: '180K+',
      },
      {
        id: 'screen-recorder',
        name: 'Screen Recorder',
        description: 'Record screen activity',
        category: 'Audio/Video',
        icon: 'fas fa-record-vinyl',
        route: '/tool/screen-recorder',
        usageCount: '200K+',
      },
      
    ],
  },
  {
    id: 'government',
    name: 'Govt Documents',
    description: 'Indian government document tools with 15 utilities for PAN, Aadhaar, certificates, and official forms.',
    icon: 'fas fa-landmark',
    route: '/toolkit/government',
    color: 'orange',
    toolCount: 15,
    tools: [
      {
        id: 'pan-validator',
        name: 'PAN Validator',
        description: 'Validate PAN card format',
        category: 'Government',
        icon: 'fas fa-address-card',
        route: '/tool/pan-validator',
        usageCount: '75K+',
        featured: true,
      },
      {
        id: 'aadhaar-validator',
        name: 'Aadhaar Validator',
        description: 'Validate Aadhaar card format',
        category: 'Government',
        icon: 'fas fa-fingerprint',
        route: '/tool/aadhaar-validator',
        usageCount: '85K+',
      },
      {
        id: 'voter-id-validator',
        name: 'Voter ID Validator',
        description: 'Validate Voter ID card format',
        category: 'Government',
        icon: 'fas fa-check-to-slot',
        route: '/tool/voter-id-validator',
        usageCount: '45K+',
      },
      {
        id: 'passport-validator',
        name: 'Passport Validator',
        description: 'Validate Indian passport format',
        category: 'Government',
        icon: 'fas fa-plane-departure',
        route: '/tool/passport-validator',
        usageCount: '35K+',
      },
      {
        id: 'driving-license-validator',
        name: 'Driving License Validator',
        description: 'Validate driving license format',
        category: 'Government',
        icon: 'fas fa-car-side',
        route: '/tool/driving-license-validator',
        usageCount: '55K+',
      },
      {
        id: 'gst-validator',
        name: 'GST Number Validator',
        description: 'Validate GST identification number',
        category: 'Government',
        icon: 'fas fa-file-invoice',
        route: '/tool/gst-validator',
        usageCount: '120K+',
      },
      {
        id: 'ifsc-validator',
        name: 'IFSC Code Validator',
        description: 'Validate bank IFSC codes',
        category: 'Government',
        icon: 'fas fa-landmark',
        route: '/tool/ifsc-validator',
        usageCount: '200K+',
      },
      {
        id: 'cin-validator',
        name: 'CIN Validator',
        description: 'Validate Corporate Identity Number',
        category: 'Government',
        icon: 'fas fa-briefcase',
        route: '/tool/cin-validator',
        usageCount: '40K+',
      },
      {
        id: 'udyam-validator',
        name: 'Udyam Registration Validator',
        description: 'Validate Udyam registration number',
        category: 'Government',
        icon: 'fas fa-factory',
        route: '/tool/udyam-validator',
        usageCount: '25K+',
      },
      {
        id: 'tan-validator',
        name: 'TAN Validator',
        description: 'Validate Tax Deduction Account Number',
        category: 'Government',
        icon: 'fas fa-percent',
        route: '/tool/tan-validator',
        usageCount: '30K+',
      },
      {
        id: 'esi-validator',
        name: 'ESI Number Validator',
        description: 'Validate Employee State Insurance number',
        category: 'Government',
        icon: 'fas fa-user-injured',
        route: '/tool/esi-validator',
        usageCount: '20K+',
      },
      {
        id: 'pf-validator',
        name: 'PF Number Validator',
        description: 'Validate Provident Fund number',
        category: 'Government',
        icon: 'fas fa-coins',
        route: '/tool/pf-validator',
        usageCount: '35K+',
      },
      {
        id: 'uan-validator',
        name: 'UAN Validator',
        description: 'Validate Universal Account Number',
        category: 'Government',
        icon: 'fas fa-user-check',
        route: '/tool/uan-validator',
        usageCount: '45K+',
      },
      {
        id: 'fssai-validator',
        name: 'FSSAI License Validator',
        description: 'Validate FSSAI license number',
        category: 'Government',
        icon: 'fas fa-apple-alt',
        route: '/tool/fssai-validator',
        usageCount: '15K+',
      },
      {
        id: 'ration-card-status',
        name: 'Ration Card Status',
        description: 'Check ration card status online',
        category: 'Government',
        icon: 'fas fa-wheat-awn',
        route: '/tool/ration-card-status',
        usageCount: '150K+',
      },
      {
        id: 'shop-act-validator',
        name: 'Shop Act License Validator',
        description: 'Validate Shop Act license format',
        category: 'Government',
        icon: 'fas fa-store-alt',
        route: '/tool/shop-act-validator',
        usageCount: '18K+',
      },
      
    ],
  },
  {
    id: 'developer',
    name: 'Developer Toolkit',
    description: 'Essential development tools with 28 utilities for coding, formatting, conversion, and creative tasks.',
    icon: 'fas fa-code',
    route: '/toolkit/developer',
    color: 'blue',
    toolCount: 28,
    tools: [
      {
        id: 'barcode-generator',
        name: 'Barcode Generator',
        description: 'Generate barcodes for products',
        category: 'Developer',
        icon: 'fas fa-barcode',
        route: '/tool/barcode-generator',
        usageCount: '45K+',
      },
      {
        id: 'base64-encoder',
        name: 'Base64 Encoder/Decoder',
        description: 'Encode and decode Base64 strings',
        category: 'Developer',
        icon: 'fas fa-file-code',
        route: '/tool/base64-encoder',
        usageCount: '85K+',
        featured: true,
      },
      {
        id: 'css-minifier',
        name: 'CSS Minifier',
        description: 'Minify CSS code for better performance',
        category: 'Developer',
        icon: 'fab fa-css3-alt',
        route: '/tool/css-minifier',
        usageCount: '65K+',
      },
      {
        id: 'csv-to-json',
        name: 'CSV to JSON Converter',
        description: 'Convert CSV data to JSON format',
        category: 'Developer',
        icon: 'fas fa-table',
        route: '/tool/csv-to-json',
        usageCount: '75K+',
      },
      {
        id: 'favicon-generator',
        name: 'Favicon Generator',
        description: 'Generate favicons for websites',
        category: 'Developer',
        icon: 'fas fa-globe',
        route: '/tool/favicon-generator',
        usageCount: '55K+',
      },
      {
        id: 'gradient-generator',
        name: 'CSS Gradient Generator',
        description: 'Create beautiful CSS gradients',
        category: 'Developer',
        icon: 'fas fa-paint-roller',
        route: '/tool/gradient-generator',
        usageCount: '90K+',
        featured: true,
      },
      {
        id: 'hash-generator',
        name: 'Hash Generator',
        description: 'Generate MD5, SHA1, SHA256 hashes',
        category: 'Developer',
        icon: 'fas fa-key',
        route: '/tool/hash-generator',
        usageCount: '60K+',
      },
      {
        id: 'html-to-pdf',
        name: 'HTML to PDF',
        description: 'Convert HTML content to PDF',
        category: 'Developer',
        icon: 'fab fa-html5',
        route: '/tool/html-to-pdf',
        usageCount: '120K+',
      },
      {
        id: 'js-minifier',
        name: 'JavaScript Minifier',
        description: 'Minify JavaScript code',
        category: 'Developer',
        icon: 'fab fa-js-square',
        route: '/tool/js-minifier',
        usageCount: '70K+',
      },
      {
        id: 'json-formatter',
        name: 'JSON Formatter',
        description: 'Format and validate JSON data',
        category: 'Developer',
        icon: 'fas fa-brackets-curly',
        route: '/tool/json-formatter',
        usageCount: '150K+',
        featured: true,
      },
      {
        id: 'lorem-ipsum-generator',
        name: 'Lorem Ipsum Generator',
        description: 'Generate placeholder text',
        category: 'Developer',
        icon: 'fas fa-align-left',
        route: '/tool/lorem-ipsum-generator',
        usageCount: '40K+',
      },
      {
        id: 'markdown-to-html',
        name: 'Markdown to HTML',
        description: 'Convert Markdown to HTML',
        category: 'Developer',
        icon: 'fab fa-markdown',
        route: '/tool/markdown-to-html',
        usageCount: '80K+',
      },
      {
        id: 'meta-tag-generator',
        name: 'Meta Tag Generator',
        description: 'Generate SEO meta tags',
        category: 'Developer',
        icon: 'fas fa-search-location',
        route: '/tool/meta-tag-generator',
        usageCount: '95K+',
      },
      {
        id: 'password-generator',
        name: 'Password Generator',
        description: 'Generate secure passwords',
        category: 'Developer',
        icon: 'fas fa-user-lock',
        route: '/tool/password-generator',
        usageCount: '200K+',
        featured: true,
      },
      {
        id: 'qr-generator',
        name: 'QR Code Generator',
        description: 'Generate QR codes for any text',
        category: 'Developer',
        icon: 'fas fa-qrcode',
        route: '/tool/qr-generator',
        usageCount: '180K+',
      },
      {
        id: 'regex-tester',
        name: 'Regex Tester',
        description: 'Test and validate regular expressions',
        category: 'Developer',
        icon: 'fas fa-magnifying-glass',
        route: '/tool/regex-tester',
        usageCount: '110K+',
      },
      {
        id: 'timestamp-converter',
        name: 'Timestamp Converter',
        description: 'Convert between timestamp formats',
        category: 'Developer',
        icon: 'fas fa-clock-rotate-left',
        route: '/tool/timestamp-converter',
        usageCount: '85K+',
      },
      {
        id: 'unicode-converter',
        name: 'Unicode Converter',
        description: 'Convert between Unicode formats',
        category: 'Developer',
        icon: 'fas fa-language',
        route: '/tool/unicode-converter',
        usageCount: '50K+',
      },
      {
        id: 'unit-converter',
        name: 'Unit Converter',
        description: 'Convert between different units',
        category: 'Developer',
        icon: 'fas fa-ruler-combined',
        route: '/tool/unit-converter',
        usageCount: '130K+',
      },
      {
        id: 'url-shortener',
        name: 'URL Shortener',
        description: 'Create short URLs',
        category: 'Developer',
        icon: 'fas fa-link',
        route: '/tool/url-shortener',
        usageCount: '160K+',
      },
      {
        id: 'xml-formatter',
        name: 'XML Formatter',
        description: 'Format and validate XML data',
        category: 'Developer',
        icon: 'fas fa-file-lines',
        route: '/tool/xml-formatter',
        usageCount: '45K+',
      },
      {
        id: 'color-palette-generator',
        name: 'Color Palette Generator',
        description: 'Generate beautiful color palettes',
        category: 'Developer',
        icon: 'fas fa-swatchbook',
        route: '/tool/color-palette-generator',
        usageCount: '100K+',
      },
      {
        id: 'logo-generator',
        name: 'Logo Generator',
        description: 'Create logos with AI',
        category: 'Developer',
        icon: 'fas fa-award',
        route: '/tool/logo-generator',
        usageCount: '90K+',
      },
      {
        id: 'speech-to-text',
        name: 'Speech to Text',
        description: 'Convert speech to text',
        category: 'Developer',
        icon: 'fas fa-microphone-alt',
        route: '/tool/speech-to-text',
        usageCount: '140K+',
      },
      {
        id: 'text-to-speech',
        name: 'Text to Speech',
        description: 'Convert text to speech',
        category: 'Developer',
        icon: 'fas fa-volume-high',
        route: '/tool/text-to-speech',
        usageCount: '120K+',
      },
      {
        id: 'video-to-audio',
        name: 'Video to Audio',
        description: 'Extract audio from video files',
        category: 'Developer',
        icon: 'fas fa-waveform-lines',
        route: '/tool/video-to-audio',
        usageCount: '200K+',
      },
      {
        id: 'image-flipper',
        name: 'Image Flipper',
        description: 'Flip images horizontally or vertically',
        category: 'Developer',
        icon: 'fas fa-arrows-rotate',
        route: '/tool/image-flipper',
        usageCount: '80K+',
      },
      {
        id: 'image-format-converter',
        name: 'Image Format Converter',
        description: 'Convert between image formats',
        category: 'Developer',
        icon: 'fas fa-image',
        route: '/tool/image-format-converter',
        usageCount: '150K+',
      }
    ],
  },
];

export const getFeaturedTools = (): Tool[] => {
  return toolkits.flatMap(toolkit => toolkit.tools.filter(tool => tool.featured));
};

export const getToolkitById = (id: string): Toolkit | undefined => {
  return toolkits.find(toolkit => toolkit.id === id);
};

export const getToolById = (id: string): Tool | undefined => {
  for (const toolkit of toolkits) {
    const tool = toolkit.tools.find(tool => tool.id === id);
    if (tool) return tool;
  }
  return undefined;
};

export const getColorClasses = (color: string) => {
  const colorMap = {
    red: {
      bg: 'bg-red-100',
      text: 'text-red-600',
      border: 'border-red-500',
      hover: 'hover:border-red-500',
    },
    purple: {
      bg: 'bg-purple-100',
      text: 'text-purple-600',
      border: 'border-purple-500',
      hover: 'hover:border-purple-500',
    },
    green: {
      bg: 'bg-green-100',
      text: 'text-green-600',
      border: 'border-green-500',
      hover: 'hover:border-green-500',
    },
    orange: {
      bg: 'bg-orange-100',
      text: 'text-orange-600',
      border: 'border-orange-500',
      hover: 'hover:border-orange-500',
    },
    blue: {
      bg: 'bg-blue-100',
      text: 'text-blue-600',
      border: 'border-blue-500',
      hover: 'hover:border-blue-500',
    },
  };

  return colorMap[color as keyof typeof colorMap] || colorMap.blue;
};