import {
  FileText, Scissors, Archive, FileImage, Download, Lock, Unlock,
  RotateCw, Crop, Bookmark, Edit, FileSignature, Type, Image as ImageIcon,
  FolderOpen, Info, Settings, Shuffle, Upload, Merge, Split,
  Resize, Palette, Wand2, ZoomIn, Paintbrush, Trash2, Plus,
  Blur, Sun, Sliders, Filter, Square, AlignLeft, Grid3X3,
  Camera, Music, Video, Headphones, Film, Mic, Volume2,
  VolumeX, Play, Pause, FastForward, Rewind, SkipForward,
  CreditCard, Fingerprint, Vote, MapPin, Building, FileCheck,
  Shield, Eye, Car, Landmark, Briefcase, Award,
  QrCode, BarChart, Code, Css3, Hash, Link, Globe,
  Calendar, Clock, Ruler, Palette as PaletteIcon, Type as TypeIcon,
  Search, Copy, FileJson, Minimize2, ImagePlus, Zap
} from 'lucide-react';

export const toolIconMap: Record<string, any> = {
  // PDF Tools
  'pdf-merger': Merge,
  'pdf-splitter': Split,
  'pdf-compressor': Archive,
  'pdf-to-word': FileText,
  'pdf-to-excel': FileText,
  'pdf-to-powerpoint': FileText,
  'word-to-pdf': FileText,
  'excel-to-pdf': FileText,
  'powerpoint-to-pdf': FileText,
  'pdf-ocr': Type,
  'pdf-watermark': ImageIcon,
  'pdf-password-remover': Unlock,
  'pdf-password-protector': Lock,
  'pdf-rotator': RotateCw,
  'pdf-cropper': Crop,
  'pdf-page-extractor': Scissors,
  'pdf-page-numberer': Hash,
  'pdf-bookmark-manager': Bookmark,
  'pdf-form-filler': Edit,
  'pdf-signature-adder': FileSignature,
  'pdf-text-extractor': Type,
  'pdf-image-extractor': ImageIcon,
  'pdf-organizer': FolderOpen,
  'pdf-metadata-editor': Info,
  'pdf-version-converter': Settings,

  // Image Tools
  'image-resizer': Resize,
  'bg-remover': Scissors,
  'image-compressor': Archive,
  'image-converter': Shuffle,
  'image-cropper': Crop,
  'image-rotator': RotateCw,
  'image-enhancer': Wand2,
  'image-upscaler': ZoomIn,
  'image-colorizer': Palette,
  'image-watermark-remover': Trash2,
  'image-watermark-adder': Plus,
  'image-blur-tool': Blur,
  'image-brightness-adjuster': Sun,
  'image-saturation-tool': Sliders,
  'image-filter-effects': Filter,
  'image-border-adder': Square,
  'image-text-overlay': AlignLeft,
  'image-collage-maker': Grid3X3,
  'image-metadata-extractor': Info,
  'image-batch-processor': FolderOpen,

  // Media Tools
  'audio-converter': Music,
  'video-converter': Video,
  'audio-compressor': Archive,
  'video-compressor': Archive,
  'audio-trimmer': Scissors,
  'video-trimmer': Scissors,
  'audio-merger': Merge,
  'video-merger': Merge,
  'video-to-gif': Film,
  'gif-to-video': Video,
  'audio-volume-adjuster': Volume2,
  'video-brightness-adjuster': Sun,
  'audio-format-converter': Music,
  'video-format-converter': Video,
  'video-to-audio': Headphones,
  'audio-to-video': Video,
  'video-speed-changer': FastForward,
  'video-frame-extractor': Camera,
  'audio-noise-reducer': VolumeX,
  'video-subtitle-adder': Type,

  // Government Tools
  'pan-validator': CreditCard,
  'gst-validator': Building,
  'aadhaar-validator': Fingerprint,
  'voter-id-validator': Vote,
  'passport-validator': MapPin,
  'driving-license-validator': Car,
  'ifsc-validator': Landmark,
  'cin-validator': Building,
  'udyam-validator': Briefcase,
  'tan-validator': FileCheck,
  'esi-validator': Shield,
  'pf-validator': Eye,
  'uan-validator': Award,
  'fssai-validator': Shield,
  'shop-act-validator': Building,

  // Developer Tools
  'qr-generator': QrCode,
  'barcode-generator': BarChart,
  'json-formatter': Code,
  'css-minifier': Css3,
  'js-minifier': Code,
  'html-minifier': Code,
  'base64-encoder': Hash,
  'url-shortener': Link,
  'password-generator': Lock,
  'hash-generator': Hash,
  'color-picker': Palette,
  'gradient-generator': PaletteIcon,
  'lorem-ipsum-generator': TypeIcon,
  'regex-tester': Search,
  'timestamp-converter': Clock,
  'unit-converter': Ruler,
  'uuid-generator': Hash,
  'meta-tag-generator': Code,
  'favicon-generator': ImageIcon,
  'logo-generator': Zap
};

export function getToolIcon(toolId: string) {
  return toolIconMap[toolId] || FileText;
}