services:
  - type: web
    name: suntyn-ai-backend
    env: python
    buildCommand: "pip install -r requirements-clean.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=10000"
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health